version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: skopia-sqlserver
    environment:
      - SA_PASSWORD=Your_password123
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - skopia-sqlserver-data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: skopia-tasks-api
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=TasksDb;User=sa;Password=Your_password123;TrustServerCertificate=true;
    ports:
      - "5001:8080"

volumes:
  skopia-sqlserver-data:
